### ISSUE TITLE
login! method fail

### ISSUE THREAD

**Issue by sbvitok** [mamantoha/vkontakte_client#5]
Нужно было сегодня получить access_token а не тут то было, на выполнение метода login! получаю следующую ошибку:
`NoMethodError: undefined method `match' for nil:NilClass
from /home/viktor/.gem/ruby/2.6.0/gems/vkontakte-1.7.0/lib/vkontakte/client.rb:79:in `get_token'`
Стал копаться что не так, выяснил что авторизация перестала работать,
после выполнения "page = login_form.submit" перебрасывают на главную и при этом "page.uri.fragment" пустой

**Comment by mamantoha** [comment]
У меня все работает ©
